name: 'test'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/${{ env.ANDROID_BUILD_TOOLS_VERSION }}" >> $GITHUB_PATH
      shell: bash
    - run: yes | sdkmanager --licenses
      shell: bash
    - run: sdkmanager --install ${ANDROID_SDK_PACKAGES}
      shell: bash
    - run: echo "no" | avdmanager --verbose create avd --force -n $EMULATOR_NAME --abi "${ANDROID_TARGET}/${ANDROID_ARCH}" -k "system-images;android-${API_LEVEL};${ANDROID_TARGET};${ANDROID_ARCH}"
      shell: bash
    - run: chmod +x ./start_emu_headless.sh
      shell: bash
    - run: EMULATOR_TIMEOUT=$EMULATOR_TIMEOUT EMULATOR_NAME=$EMULATOR_NAME ./start_emu_headless.sh
      shell: bash
    - run: chmod a+x ./check_emu.sh
      shell: bash
    - run: ./check_emu.sh
      shell: bash
    - run:  curl -sS https://dl.google.com/appcrawler/beta1/app-crawler.zip > file.zip
      shell: bash
    - run: unzip file.zip
      shell: bash
    - run: rm file.zip
      shell: bash
    - run: java -jar app-crawler/crawl_launcher.jar --apk-file ${{inputs.app-location}} --android-sdk $ANDROID_HOME/ --app-package-name ${{ inputs.app-package-name }}
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
